package c29.jad.controllers;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.servlet.ModelAndView;

@Controller
//@RequestMapping(value = "page")
public class PageController {

    @RequestMapping(value = "/", method = RequestMethod.GET)
    public String index(){
        return "index";
    }

    @RequestMapping(value ="/model")
    public String model(Model model){
        model.addAttribute("message","Hello World");
        return "index";
    }

    @RequestMapping(value = "/test", method = RequestMethod.GET)
    public ModelAndView testing(){
        var modelAndView = new ModelAndView("index");
        modelAndView.addObject("message","Generated by Thymeleaf");
        return modelAndView;
    }

    @RequestMapping(value = "/login", method = RequestMethod.GET)
    public String login(Model model){
        model.addAttribute("loginNow", "Please login first");
        return "login";
    }



}
